apiVersion: v1
kind: Service
metadata:
  name: sample-node
  namespace: nordcloud
spec:
  clusterIP: 10.103.186.163
  clusterIPs:
  - 10.103.186.163
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30199
    port: 8080
    protocol: TCP
    targetPort: 7777
  selector:
    app: sample-node
  sessionAffinity: None
  type: NodePort

