apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lbg-dev-argo-nginx-ns
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: glaceroy/nginx:v1.2
        name: nginx
        resources:
          requests:
            cpu: "20m"
            memory: "55Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"    
        ports:
        - containerPort:  80
          name:  nginx-port